//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudCommerceProApiClient.CloudCommercePro.Customers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfAPICustomerAddCustomerRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfAPICustomerAddCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerAddCustomerRequest ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerAddCustomerRequest Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICustomerAddCustomerRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APICustomerAddCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int intBrandIDField;
        
        private int SalesChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        private int intCustomerTypeField;
        
        private int intPaymentTermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobNoField;
        
        private System.Nullable<int> LoginIDField;
        
        private System.Nullable<int> AgentIDField;
        
        private System.Nullable<float> CreditLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int intBrandID {
            get {
                return this.intBrandIDField;
            }
            set {
                if ((this.intBrandIDField.Equals(value) != true)) {
                    this.intBrandIDField = value;
                    this.RaisePropertyChanged("intBrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int SalesChannelID {
            get {
                return this.SalesChannelIDField;
            }
            set {
                if ((this.SalesChannelIDField.Equals(value) != true)) {
                    this.SalesChannelIDField = value;
                    this.RaisePropertyChanged("SalesChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TradingName {
            get {
                return this.TradingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingNameField, value) != true)) {
                    this.TradingNameField = value;
                    this.RaisePropertyChanged("TradingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int intCustomerType {
            get {
                return this.intCustomerTypeField;
            }
            set {
                if ((this.intCustomerTypeField.Equals(value) != true)) {
                    this.intCustomerTypeField = value;
                    this.RaisePropertyChanged("intCustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int intPaymentTerms {
            get {
                return this.intPaymentTermsField;
            }
            set {
                if ((this.intPaymentTermsField.Equals(value) != true)) {
                    this.intPaymentTermsField = value;
                    this.RaisePropertyChanged("intPaymentTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string VATNumber {
            get {
                return this.VATNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VATNumberField, value) != true)) {
                    this.VATNumberField = value;
                    this.RaisePropertyChanged("VATNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TownCity {
            get {
                return this.TownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TownCityField, value) != true)) {
                    this.TownCityField = value;
                    this.RaisePropertyChanged("TownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CountyRegion {
            get {
                return this.CountyRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyRegionField, value) != true)) {
                    this.CountyRegionField = value;
                    this.RaisePropertyChanged("CountyRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNoField, value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string FaxNo {
            get {
                return this.FaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNoField, value) != true)) {
                    this.FaxNoField = value;
                    this.RaisePropertyChanged("FaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string MobNo {
            get {
                return this.MobNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobNoField, value) != true)) {
                    this.MobNoField = value;
                    this.RaisePropertyChanged("MobNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<int> LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<int> AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((this.AgentIDField.Equals(value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<float> CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((this.CreditLimitField.Equals(value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfAPICustomer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfAPICustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomer ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomer Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICustomer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APICustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATNumberField;
        
        private int IDField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerType CustomerTypeField;
        
        private int BrandIDField;
        
        private int SalesChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradingNameField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerPaymentTerms PaymentTermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        private int LoginIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VATNumber {
            get {
                return this.VATNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VATNumberField, value) != true)) {
                    this.VATNumberField = value;
                    this.RaisePropertyChanged("VATNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerType CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((this.CustomerTypeField.Equals(value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SalesChannelID {
            get {
                return this.SalesChannelIDField;
            }
            set {
                if ((this.SalesChannelIDField.Equals(value) != true)) {
                    this.SalesChannelIDField = value;
                    this.RaisePropertyChanged("SalesChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TradingName {
            get {
                return this.TradingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingNameField, value) != true)) {
                    this.TradingNameField = value;
                    this.RaisePropertyChanged("TradingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerPaymentTerms PaymentTerms {
            get {
                return this.PaymentTermsField;
            }
            set {
                if ((this.PaymentTermsField.Equals(value) != true)) {
                    this.PaymentTermsField = value;
                    this.RaisePropertyChanged("PaymentTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNoField, value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string FaxNo {
            get {
                return this.FaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNoField, value) != true)) {
                    this.FaxNoField = value;
                    this.RaisePropertyChanged("FaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string MobNo {
            get {
                return this.MobNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobNoField, value) != true)) {
                    this.MobNoField = value;
                    this.RaisePropertyChanged("MobNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string TownCity {
            get {
                return this.TownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TownCityField, value) != true)) {
                    this.TownCityField = value;
                    this.RaisePropertyChanged("TownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CountyRegion {
            get {
                return this.CountyRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyRegionField, value) != true)) {
                    this.CountyRegionField = value;
                    this.RaisePropertyChanged("CountyRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFault", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ApiFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RequestNodeIndexField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Customers.ErrorCodeType ccpApiErrorCodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementNameField;
        
        private int ErrorCodeField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Customers.CCPApiFaultType FaultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RequestNodeIndex {
            get {
                return this.RequestNodeIndexField;
            }
            set {
                if ((this.RequestNodeIndexField.Equals(value) != true)) {
                    this.RequestNodeIndexField = value;
                    this.RaisePropertyChanged("RequestNodeIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ErrorCodeType ccpApiErrorCodeType {
            get {
                return this.ccpApiErrorCodeTypeField;
            }
            set {
                if ((this.ccpApiErrorCodeTypeField.Equals(value) != true)) {
                    this.ccpApiErrorCodeTypeField = value;
                    this.RaisePropertyChanged("ccpApiErrorCodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.CCPApiFaultType FaultType {
            get {
                return this.FaultTypeField;
            }
            set {
                if ((this.FaultTypeField.Equals(value) != true)) {
                    this.FaultTypeField = value;
                    this.RaisePropertyChanged("FaultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICustomerType", Namespace="http://tempuri.org/")]
    public enum APICustomerType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retailer = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICustomerPaymentTerms", Namespace="http://tempuri.org/")]
    public enum APICustomerPaymentTerms : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullPaymentBeforeDespatch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DaysCredit28 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DaysCredit60 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullPaymentWith10PercentEarlyPaymentDiscount = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FiftyPercentUpfrontBalancein30Days = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyPercentDepositBalanceOnDelivery = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DirectDebit = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DaysCredit30 = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodeType", Namespace="http://tempuri.org/")]
    public enum ErrorCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBrandID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordAlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingRequiredData = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralException = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCPApiFaultType", Namespace="http://tempuri.org/")]
    public enum CCPApiFaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationFault = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationFault = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFault = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        private int ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfAPICustomerList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfAPICustomerList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerList ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomerList Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICustomerList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APICustomerList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomer[] customersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.APICustomer[] customers {
            get {
                return this.customersField;
            }
            set {
                if ((object.ReferenceEquals(this.customersField, value) != true)) {
                    this.customersField = value;
                    this.RaisePropertyChanged("customers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private bool ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudCommercePro.Customers.ICCPApiCustomerService")]
    public interface ICCPApiCustomerService {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICCPApiCustomerService/AddCustomerResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse AddCustomer(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICCPApiCustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse> AddCustomerAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICCPApiCustomerService/GetCustomerByIdResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse GetCustomerById(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICCPApiCustomerService/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse> GetCustomerByIdAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/Search", ReplyAction="http://tempuri.org/ICCPApiCustomerService/SearchResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse Search(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/Search", ReplyAction="http://tempuri.org/ICCPApiCustomerService/SearchResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse> SearchAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/TestCredentials", ReplyAction="http://tempuri.org/ICCPApiCustomerService/TestCredentialsResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiCustomerService/TestCredentials", ReplyAction="http://tempuri.org/ICCPApiCustomerService/TestCredentialsResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse> TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequestBody Body;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfAPICustomerAddCustomerRequest request;
        
        public AddCustomerRequestBody() {
        }
        
        public AddCustomerRequestBody(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfAPICustomerAddCustomerRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponseBody Body;
        
        public AddCustomerResponse() {
        }
        
        public AddCustomerResponse(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer AddCustomerResult;
        
        public AddCustomerResponseBody() {
        }
        
        public AddCustomerResponseBody(CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer AddCustomerResult) {
            this.AddCustomerResult = AddCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerById", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequestBody Body;
        
        public GetCustomerByIdRequest() {
        }
        
        public GetCustomerByIdRequest(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfInt32 request;
        
        public GetCustomerByIdRequestBody() {
        }
        
        public GetCustomerByIdRequestBody(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfInt32 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponseBody Body;
        
        public GetCustomerByIdResponse() {
        }
        
        public GetCustomerByIdResponse(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer GetCustomerByIdResult;
        
        public GetCustomerByIdResponseBody() {
        }
        
        public GetCustomerByIdResponseBody(CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer GetCustomerByIdResult) {
            this.GetCustomerByIdResult = GetCustomerByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomerList SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomerList SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCredentials", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequestBody Body;
        
        public TestCredentialsRequest() {
        }
        
        public TestCredentialsRequest(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request;
        
        public TestCredentialsRequestBody() {
        }
        
        public TestCredentialsRequestBody(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCredentialsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponseBody Body;
        
        public TestCredentialsResponse() {
        }
        
        public TestCredentialsResponse(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfBoolean TestCredentialsResult;
        
        public TestCredentialsResponseBody() {
        }
        
        public TestCredentialsResponseBody(CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfBoolean TestCredentialsResult) {
            this.TestCredentialsResult = TestCredentialsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCPApiCustomerServiceChannel : CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCPApiCustomerServiceClient : System.ServiceModel.ClientBase<CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService>, CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService {
        
        public CCPApiCustomerServiceClient() {
        }
        
        public CCPApiCustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCPApiCustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCPApiCustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCPApiCustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.AddCustomer(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer AddCustomer(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfAPICustomerAddCustomerRequest request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).AddCustomer(inValue);
            return retVal.Body.AddCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse> CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.AddCustomerAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerResponse> AddCustomerAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfAPICustomerAddCustomerRequest request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.AddCustomerRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).AddCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.GetCustomerById(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerById(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomer GetCustomerById(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).GetCustomerById(inValue);
            return retVal.Body.GetCustomerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse> CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.GetCustomerByIdAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdResponse> GetCustomerByIdAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.GetCustomerByIdRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).GetCustomerByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.Search(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfAPICustomerList Search(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse> CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.SearchAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.SearchResponse> SearchAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.SearchRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest request) {
            return base.Channel.TestCredentials(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Customers.ResponseObjectOfBoolean TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).TestCredentials(inValue);
            return retVal.Body.TestCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse> CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService.TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest request) {
            return base.Channel.TestCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsResponse> TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Customers.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Customers.TestCredentialsRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Customers.ICCPApiCustomerService)(this)).TestCredentialsAsync(inValue);
        }
    }
}
