//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudCommerceProApiClient.CloudCommercePro.OrderReturns {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        private int ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfListOfOrderReturn", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfListOfOrderReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.OrderReturn[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.OrderReturn[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderReturn", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalRefField;
        
        private System.DateTime OrderDateField;
        
        private System.DateTime ReturnDateField;
        
        private int OrderCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        private int SalesChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelTypeField;
        
        private int ChannelCountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelCountryField;
        
        private int NoOfProductsField;
        
        private int TotalItemsReturnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ReturnItem[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalRef {
            get {
                return this.ExternalRefField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalRefField, value) != true)) {
                    this.ExternalRefField = value;
                    this.RaisePropertyChanged("ExternalRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int OrderCountryID {
            get {
                return this.OrderCountryIDField;
            }
            set {
                if ((this.OrderCountryIDField.Equals(value) != true)) {
                    this.OrderCountryIDField = value;
                    this.RaisePropertyChanged("OrderCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OrderCountry {
            get {
                return this.OrderCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCountryField, value) != true)) {
                    this.OrderCountryField = value;
                    this.RaisePropertyChanged("OrderCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SalesChannelID {
            get {
                return this.SalesChannelIDField;
            }
            set {
                if ((this.SalesChannelIDField.Equals(value) != true)) {
                    this.SalesChannelIDField = value;
                    this.RaisePropertyChanged("SalesChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ChannelName {
            get {
                return this.ChannelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelNameField, value) != true)) {
                    this.ChannelNameField = value;
                    this.RaisePropertyChanged("ChannelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ChannelType {
            get {
                return this.ChannelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelTypeField, value) != true)) {
                    this.ChannelTypeField = value;
                    this.RaisePropertyChanged("ChannelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int ChannelCountryID {
            get {
                return this.ChannelCountryIDField;
            }
            set {
                if ((this.ChannelCountryIDField.Equals(value) != true)) {
                    this.ChannelCountryIDField = value;
                    this.RaisePropertyChanged("ChannelCountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ChannelCountry {
            get {
                return this.ChannelCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelCountryField, value) != true)) {
                    this.ChannelCountryField = value;
                    this.RaisePropertyChanged("ChannelCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int NoOfProducts {
            get {
                return this.NoOfProductsField;
            }
            set {
                if ((this.NoOfProductsField.Equals(value) != true)) {
                    this.NoOfProductsField = value;
                    this.RaisePropertyChanged("NoOfProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int TotalItemsReturned {
            get {
                return this.TotalItemsReturnedField;
            }
            set {
                if ((this.TotalItemsReturnedField.Equals(value) != true)) {
                    this.TotalItemsReturnedField = value;
                    this.RaisePropertyChanged("TotalItemsReturned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ReturnItem[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFault", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ApiFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RequestNodeIndexField;
        
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ErrorCodeType ccpApiErrorCodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementNameField;
        
        private int ErrorCodeField;
        
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.CCPApiFaultType FaultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RequestNodeIndex {
            get {
                return this.RequestNodeIndexField;
            }
            set {
                if ((this.RequestNodeIndexField.Equals(value) != true)) {
                    this.RequestNodeIndexField = value;
                    this.RaisePropertyChanged("RequestNodeIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ErrorCodeType ccpApiErrorCodeType {
            get {
                return this.ccpApiErrorCodeTypeField;
            }
            set {
                if ((this.ccpApiErrorCodeTypeField.Equals(value) != true)) {
                    this.ccpApiErrorCodeTypeField = value;
                    this.RaisePropertyChanged("ccpApiErrorCodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.CCPApiFaultType FaultType {
            get {
                return this.FaultTypeField;
            }
            set {
                if ((this.FaultTypeField.Equals(value) != true)) {
                    this.FaultTypeField = value;
                    this.RaisePropertyChanged("FaultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReturnItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        private int SalesChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesChannelField;
        
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        private int OrderIDField;
        
        private int OrderItemIDField;
        
        private int ProductRangeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductRangeField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductFullNameField;
        
        private int ReturnsIDField;
        
        private int ReturnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        private int ReturnCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCodeField;
        
        private int ReturnStatusCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnStatusField;
        
        private int PaymentIDField;
        
        private decimal NetAmountField;
        
        private decimal VATAmountField;
        
        private decimal GrossAmountField;
        
        private int StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SalesChannelID {
            get {
                return this.SalesChannelIDField;
            }
            set {
                if ((this.SalesChannelIDField.Equals(value) != true)) {
                    this.SalesChannelIDField = value;
                    this.RaisePropertyChanged("SalesChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SalesChannel {
            get {
                return this.SalesChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesChannelField, value) != true)) {
                    this.SalesChannelField = value;
                    this.RaisePropertyChanged("SalesChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int OrderItemID {
            get {
                return this.OrderItemIDField;
            }
            set {
                if ((this.OrderItemIDField.Equals(value) != true)) {
                    this.OrderItemIDField = value;
                    this.RaisePropertyChanged("OrderItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ProductRangeID {
            get {
                return this.ProductRangeIDField;
            }
            set {
                if ((this.ProductRangeIDField.Equals(value) != true)) {
                    this.ProductRangeIDField = value;
                    this.RaisePropertyChanged("ProductRangeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ProductRange {
            get {
                return this.ProductRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductRangeField, value) != true)) {
                    this.ProductRangeField = value;
                    this.RaisePropertyChanged("ProductRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ProductSKU {
            get {
                return this.ProductSKUField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSKUField, value) != true)) {
                    this.ProductSKUField = value;
                    this.RaisePropertyChanged("ProductSKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ProductFullName {
            get {
                return this.ProductFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductFullNameField, value) != true)) {
                    this.ProductFullNameField = value;
                    this.RaisePropertyChanged("ProductFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int ReturnsID {
            get {
                return this.ReturnsIDField;
            }
            set {
                if ((this.ReturnsIDField.Equals(value) != true)) {
                    this.ReturnsIDField = value;
                    this.RaisePropertyChanged("ReturnsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int Returns {
            get {
                return this.ReturnsField;
            }
            set {
                if ((this.ReturnsField.Equals(value) != true)) {
                    this.ReturnsField = value;
                    this.RaisePropertyChanged("Returns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int ReturnCodeID {
            get {
                return this.ReturnCodeIDField;
            }
            set {
                if ((this.ReturnCodeIDField.Equals(value) != true)) {
                    this.ReturnCodeIDField = value;
                    this.RaisePropertyChanged("ReturnCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int ReturnStatusCodeID {
            get {
                return this.ReturnStatusCodeIDField;
            }
            set {
                if ((this.ReturnStatusCodeIDField.Equals(value) != true)) {
                    this.ReturnStatusCodeIDField = value;
                    this.RaisePropertyChanged("ReturnStatusCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ReturnStatus {
            get {
                return this.ReturnStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnStatusField, value) != true)) {
                    this.ReturnStatusField = value;
                    this.RaisePropertyChanged("ReturnStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((this.PaymentIDField.Equals(value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public decimal NetAmount {
            get {
                return this.NetAmountField;
            }
            set {
                if ((this.NetAmountField.Equals(value) != true)) {
                    this.NetAmountField = value;
                    this.RaisePropertyChanged("NetAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public decimal VATAmount {
            get {
                return this.VATAmountField;
            }
            set {
                if ((this.VATAmountField.Equals(value) != true)) {
                    this.VATAmountField = value;
                    this.RaisePropertyChanged("VATAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public decimal GrossAmount {
            get {
                return this.GrossAmountField;
            }
            set {
                if ((this.GrossAmountField.Equals(value) != true)) {
                    this.GrossAmountField = value;
                    this.RaisePropertyChanged("GrossAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodeType", Namespace="http://tempuri.org/")]
    public enum ErrorCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBrandID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordAlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingRequiredData = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralException = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCPApiFaultType", Namespace="http://tempuri.org/")]
    public enum CCPApiFaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationFault = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationFault = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFault = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfOrderReturnsQuery", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfOrderReturnsQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.OrderReturns.OrderReturnsQuery ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.OrderReturnsQuery Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderReturnsQuery", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderReturnsQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService")]
    public interface ICcpApiOrderReturnsService {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcpApiOrderReturnsService/GetOutstandingReturns", ReplyAction="http://tempuri.org/ICcpApiOrderReturnsService/GetOutstandingReturnsResponse")]
        CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse GetOutstandingReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcpApiOrderReturnsService/GetOutstandingReturns", ReplyAction="http://tempuri.org/ICcpApiOrderReturnsService/GetOutstandingReturnsResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse> GetOutstandingReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcpApiOrderReturnsService/GetReturns", ReplyAction="http://tempuri.org/ICcpApiOrderReturnsService/GetReturnsResponse")]
        CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse GetReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcpApiOrderReturnsService/GetReturns", ReplyAction="http://tempuri.org/ICcpApiOrderReturnsService/GetReturnsResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse> GetReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutstandingReturnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutstandingReturns", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequestBody Body;
        
        public GetOutstandingReturnsRequest() {
        }
        
        public GetOutstandingReturnsRequest(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOutstandingReturnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfInt32 request;
        
        public GetOutstandingReturnsRequestBody() {
        }
        
        public GetOutstandingReturnsRequestBody(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfInt32 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutstandingReturnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutstandingReturnsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponseBody Body;
        
        public GetOutstandingReturnsResponse() {
        }
        
        public GetOutstandingReturnsResponse(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOutstandingReturnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetOutstandingReturnsResult;
        
        public GetOutstandingReturnsResponseBody() {
        }
        
        public GetOutstandingReturnsResponseBody(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetOutstandingReturnsResult) {
            this.GetOutstandingReturnsResult = GetOutstandingReturnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReturnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReturns", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequestBody Body;
        
        public GetReturnsRequest() {
        }
        
        public GetReturnsRequest(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReturnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfOrderReturnsQuery request;
        
        public GetReturnsRequestBody() {
        }
        
        public GetReturnsRequestBody(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfOrderReturnsQuery request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReturnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReturnsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponseBody Body;
        
        public GetReturnsResponse() {
        }
        
        public GetReturnsResponse(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReturnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetReturnsResult;
        
        public GetReturnsResponseBody() {
        }
        
        public GetReturnsResponseBody(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetReturnsResult) {
            this.GetReturnsResult = GetReturnsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICcpApiOrderReturnsServiceChannel : CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CcpApiOrderReturnsServiceClient : System.ServiceModel.ClientBase<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService>, CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService {
        
        public CcpApiOrderReturnsServiceClient() {
        }
        
        public CcpApiOrderReturnsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CcpApiOrderReturnsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CcpApiOrderReturnsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CcpApiOrderReturnsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService.GetOutstandingReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest request) {
            return base.Channel.GetOutstandingReturns(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetOutstandingReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService)(this)).GetOutstandingReturns(inValue);
            return retVal.Body.GetOutstandingReturnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse> CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService.GetOutstandingReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest request) {
            return base.Channel.GetOutstandingReturnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsResponse> GetOutstandingReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetOutstandingReturnsRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService)(this)).GetOutstandingReturnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService.GetReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest request) {
            return base.Channel.GetReturns(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ResponseObjectOfListOfOrderReturn GetReturns(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfOrderReturnsQuery request) {
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService)(this)).GetReturns(inValue);
            return retVal.Body.GetReturnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse> CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService.GetReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest request) {
            return base.Channel.GetReturnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsResponse> GetReturnsAsync(CloudCommerceProApiClient.CloudCommercePro.OrderReturns.RequestObjectOfOrderReturnsQuery request) {
            CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.OrderReturns.GetReturnsRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.OrderReturns.ICcpApiOrderReturnsService)(this)).GetReturnsAsync(inValue);
        }
    }
}
