//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudCommerceProApiClient.CloudCommercePro.Payments {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        private int ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfListOfAPIPaymentBankAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfListOfAPIPaymentBankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Payments.APIPaymentBankAccount[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.APIPaymentBankAccount[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIPaymentBankAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIPaymentBankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankSortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BankSortCode {
            get {
                return this.BankSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankSortCodeField, value) != true)) {
                    this.BankSortCodeField = value;
                    this.RaisePropertyChanged("BankSortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BankAccountNo {
            get {
                return this.BankAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNoField, value) != true)) {
                    this.BankAccountNoField = value;
                    this.RaisePropertyChanged("BankAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BankAccountName {
            get {
                return this.BankAccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNameField, value) != true)) {
                    this.BankAccountNameField = value;
                    this.RaisePropertyChanged("BankAccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFault", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ApiFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RequestNodeIndexField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Payments.ErrorCodeType ccpApiErrorCodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementNameField;
        
        private int ErrorCodeField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Payments.CCPApiFaultType FaultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RequestNodeIndex {
            get {
                return this.RequestNodeIndexField;
            }
            set {
                if ((this.RequestNodeIndexField.Equals(value) != true)) {
                    this.RequestNodeIndexField = value;
                    this.RaisePropertyChanged("RequestNodeIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ErrorCodeType ccpApiErrorCodeType {
            get {
                return this.ccpApiErrorCodeTypeField;
            }
            set {
                if ((this.ccpApiErrorCodeTypeField.Equals(value) != true)) {
                    this.ccpApiErrorCodeTypeField = value;
                    this.RaisePropertyChanged("ccpApiErrorCodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.CCPApiFaultType FaultType {
            get {
                return this.FaultTypeField;
            }
            set {
                if ((this.FaultTypeField.Equals(value) != true)) {
                    this.FaultTypeField = value;
                    this.RaisePropertyChanged("FaultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodeType", Namespace="http://tempuri.org/")]
    public enum ErrorCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBrandID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordAlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingRequiredData = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralException = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCPApiFaultType", Namespace="http://tempuri.org/")]
    public enum CCPApiFaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationFault = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationFault = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFault = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfAPIPaymentAddPaymentRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfAPIPaymentAddPaymentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Payments.APIPaymentAddPaymentRequest ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.APIPaymentAddPaymentRequest Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIPaymentAddPaymentRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIPaymentAddPaymentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int intInvoiceIDField;
        
        private int intProformaIDField;
        
        private int intBrandIDField;
        
        private int intSalesChannelIDField;
        
        private int intBankAccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPaymentReferenceField;
        
        private double dbPaymentNetAmountField;
        
        private double dbPaymentTaxAmountField;
        
        private double dbPaymentAmountField;
        
        private double dbGBPPaymentAmountField;
        
        private double dbPostagePaymentAmountField;
        
        private double dbPostageGBPPaymentAmountField;
        
        private System.DateTime dtPaymentDateField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Payments.TransactionTypeID TransactionTypeIDField;
        
        private int intCustomerIDField;
        
        private CloudCommerceProApiClient.CloudCommercePro.Payments.PaymentGatewayType GatewayTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int intInvoiceID {
            get {
                return this.intInvoiceIDField;
            }
            set {
                if ((this.intInvoiceIDField.Equals(value) != true)) {
                    this.intInvoiceIDField = value;
                    this.RaisePropertyChanged("intInvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int intProformaID {
            get {
                return this.intProformaIDField;
            }
            set {
                if ((this.intProformaIDField.Equals(value) != true)) {
                    this.intProformaIDField = value;
                    this.RaisePropertyChanged("intProformaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int intBrandID {
            get {
                return this.intBrandIDField;
            }
            set {
                if ((this.intBrandIDField.Equals(value) != true)) {
                    this.intBrandIDField = value;
                    this.RaisePropertyChanged("intBrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int intSalesChannelID {
            get {
                return this.intSalesChannelIDField;
            }
            set {
                if ((this.intSalesChannelIDField.Equals(value) != true)) {
                    this.intSalesChannelIDField = value;
                    this.RaisePropertyChanged("intSalesChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int intBankAccountID {
            get {
                return this.intBankAccountIDField;
            }
            set {
                if ((this.intBankAccountIDField.Equals(value) != true)) {
                    this.intBankAccountIDField = value;
                    this.RaisePropertyChanged("intBankAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strPaymentReference {
            get {
                return this.strPaymentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.strPaymentReferenceField, value) != true)) {
                    this.strPaymentReferenceField = value;
                    this.RaisePropertyChanged("strPaymentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double dbPaymentNetAmount {
            get {
                return this.dbPaymentNetAmountField;
            }
            set {
                if ((this.dbPaymentNetAmountField.Equals(value) != true)) {
                    this.dbPaymentNetAmountField = value;
                    this.RaisePropertyChanged("dbPaymentNetAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double dbPaymentTaxAmount {
            get {
                return this.dbPaymentTaxAmountField;
            }
            set {
                if ((this.dbPaymentTaxAmountField.Equals(value) != true)) {
                    this.dbPaymentTaxAmountField = value;
                    this.RaisePropertyChanged("dbPaymentTaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double dbPaymentAmount {
            get {
                return this.dbPaymentAmountField;
            }
            set {
                if ((this.dbPaymentAmountField.Equals(value) != true)) {
                    this.dbPaymentAmountField = value;
                    this.RaisePropertyChanged("dbPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double dbGBPPaymentAmount {
            get {
                return this.dbGBPPaymentAmountField;
            }
            set {
                if ((this.dbGBPPaymentAmountField.Equals(value) != true)) {
                    this.dbGBPPaymentAmountField = value;
                    this.RaisePropertyChanged("dbGBPPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double dbPostagePaymentAmount {
            get {
                return this.dbPostagePaymentAmountField;
            }
            set {
                if ((this.dbPostagePaymentAmountField.Equals(value) != true)) {
                    this.dbPostagePaymentAmountField = value;
                    this.RaisePropertyChanged("dbPostagePaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double dbPostageGBPPaymentAmount {
            get {
                return this.dbPostageGBPPaymentAmountField;
            }
            set {
                if ((this.dbPostageGBPPaymentAmountField.Equals(value) != true)) {
                    this.dbPostageGBPPaymentAmountField = value;
                    this.RaisePropertyChanged("dbPostageGBPPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime dtPaymentDate {
            get {
                return this.dtPaymentDateField;
            }
            set {
                if ((this.dtPaymentDateField.Equals(value) != true)) {
                    this.dtPaymentDateField = value;
                    this.RaisePropertyChanged("dtPaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.TransactionTypeID TransactionTypeID {
            get {
                return this.TransactionTypeIDField;
            }
            set {
                if ((this.TransactionTypeIDField.Equals(value) != true)) {
                    this.TransactionTypeIDField = value;
                    this.RaisePropertyChanged("TransactionTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int intCustomerID {
            get {
                return this.intCustomerIDField;
            }
            set {
                if ((this.intCustomerIDField.Equals(value) != true)) {
                    this.intCustomerIDField = value;
                    this.RaisePropertyChanged("intCustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.PaymentGatewayType GatewayType {
            get {
                return this.GatewayTypeField;
            }
            set {
                if ((this.GatewayTypeField.Equals(value) != true)) {
                    this.GatewayTypeField = value;
                    this.RaisePropertyChanged("GatewayType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionTypeID", Namespace="http://tempuri.org/")]
    public enum TransactionTypeID : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cash = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardPayment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChequePayment = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StandingOrder = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DirectDebit = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BACS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineBankingTransfer = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refund = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditNote = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentGateway = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentGatewayType", Namespace="http://tempuri.org/")]
    public enum PaymentGatewayType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SagePay = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardSave = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CashFlows = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HSBC = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmazonPayments = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Amazon = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecureTrading = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorldPay = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stripe = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private int ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObjectOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestObjectOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityHash {
            get {
                return this.SecurityHashField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityHashField, value) != true)) {
                    this.SecurityHashField = value;
                    this.RaisePropertyChanged("SecurityHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObjectOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseObjectOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private int ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private bool ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Content {
            get {
                return this.ContentField;
            }
            set {
                if ((this.ContentField.Equals(value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ApiFault[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudCommercePro.Payments.ICCPApiPaymentService")]
    public interface ICCPApiPaymentService {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/getBankAccounts", ReplyAction="http://tempuri.org/ICCPApiPaymentService/getBankAccountsResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse getBankAccounts(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/getBankAccounts", ReplyAction="http://tempuri.org/ICCPApiPaymentService/getBankAccountsResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse> getBankAccountsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/CreatePayment", ReplyAction="http://tempuri.org/ICCPApiPaymentService/CreatePaymentResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse CreatePayment(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/CreatePayment", ReplyAction="http://tempuri.org/ICCPApiPaymentService/CreatePaymentResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse> CreatePaymentAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/TestCredentials", ReplyAction="http://tempuri.org/ICCPApiPaymentService/TestCredentialsResponse")]
        CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCPApiPaymentService/TestCredentials", ReplyAction="http://tempuri.org/ICCPApiPaymentService/TestCredentialsResponse")]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse> TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBankAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBankAccounts", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequestBody Body;
        
        public getBankAccountsRequest() {
        }
        
        public getBankAccountsRequest(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBankAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfInt32 request;
        
        public getBankAccountsRequestBody() {
        }
        
        public getBankAccountsRequestBody(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfInt32 request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBankAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBankAccountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponseBody Body;
        
        public getBankAccountsResponse() {
        }
        
        public getBankAccountsResponse(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBankAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfListOfAPIPaymentBankAccount getBankAccountsResult;
        
        public getBankAccountsResponseBody() {
        }
        
        public getBankAccountsResponseBody(CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfListOfAPIPaymentBankAccount getBankAccountsResult) {
            this.getBankAccountsResult = getBankAccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePayment", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequestBody Body;
        
        public CreatePaymentRequest() {
        }
        
        public CreatePaymentRequest(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfAPIPaymentAddPaymentRequest request;
        
        public CreatePaymentRequestBody() {
        }
        
        public CreatePaymentRequestBody(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfAPIPaymentAddPaymentRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponseBody Body;
        
        public CreatePaymentResponse() {
        }
        
        public CreatePaymentResponse(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfInt32 CreatePaymentResult;
        
        public CreatePaymentResponseBody() {
        }
        
        public CreatePaymentResponseBody(CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfInt32 CreatePaymentResult) {
            this.CreatePaymentResult = CreatePaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCredentials", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequestBody Body;
        
        public TestCredentialsRequest() {
        }
        
        public TestCredentialsRequest(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfString request;
        
        public TestCredentialsRequestBody() {
        }
        
        public TestCredentialsRequestBody(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfString request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCredentialsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponseBody Body;
        
        public TestCredentialsResponse() {
        }
        
        public TestCredentialsResponse(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfBoolean TestCredentialsResult;
        
        public TestCredentialsResponseBody() {
        }
        
        public TestCredentialsResponseBody(CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfBoolean TestCredentialsResult) {
            this.TestCredentialsResult = TestCredentialsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCPApiPaymentServiceChannel : CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCPApiPaymentServiceClient : System.ServiceModel.ClientBase<CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService>, CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService {
        
        public CCPApiPaymentServiceClient() {
        }
        
        public CCPApiPaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCPApiPaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCPApiPaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCPApiPaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.getBankAccounts(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest request) {
            return base.Channel.getBankAccounts(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfListOfAPIPaymentBankAccount getBankAccounts(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).getBankAccounts(inValue);
            return retVal.Body.getBankAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse> CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.getBankAccountsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest request) {
            return base.Channel.getBankAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsResponse> getBankAccountsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfInt32 request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.getBankAccountsRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).getBankAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.CreatePayment(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest request) {
            return base.Channel.CreatePayment(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfInt32 CreatePayment(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfAPIPaymentAddPaymentRequest request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).CreatePayment(inValue);
            return retVal.Body.CreatePaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse> CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.CreatePaymentAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest request) {
            return base.Channel.CreatePaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentResponse> CreatePaymentAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfAPIPaymentAddPaymentRequest request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.CreatePaymentRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).CreatePaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest request) {
            return base.Channel.TestCredentials(request);
        }
        
        public CloudCommerceProApiClient.CloudCommercePro.Payments.ResponseObjectOfBoolean TestCredentials(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequestBody();
            inValue.Body.request = request;
            CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse retVal = ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).TestCredentials(inValue);
            return retVal.Body.TestCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse> CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService.TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest request) {
            return base.Channel.TestCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsResponse> TestCredentialsAsync(CloudCommerceProApiClient.CloudCommercePro.Payments.RequestObjectOfString request) {
            CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest inValue = new CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequest();
            inValue.Body = new CloudCommerceProApiClient.CloudCommercePro.Payments.TestCredentialsRequestBody();
            inValue.Body.request = request;
            return ((CloudCommerceProApiClient.CloudCommercePro.Payments.ICCPApiPaymentService)(this)).TestCredentialsAsync(inValue);
        }
    }
}
